import { Router } from "express";
import { resolutionRateLimit, registrationRateLimit } from "../../middlewares/rate-limit";
import authRouter from "./auth";
import usersRouter from "./users";
import apiKeysRouter from "./api-keys";
import identitiesRouter from "./identities";
import agentsRouter from "./agents";
import handlesRouter from "./handles";
import agentTransfersRouter from "./agent-transfers";
import fleetRouter from "./fleet";
import agentRegistryRouter from "./agent-registry";
import publicProfilesRouter from "./public-profiles";
import programmaticRouter from "./programmatic";
import agentVerificationRouter from "./agent-verification";
import agentIdentityRouter from "./agent-identity";
import agentSpawnRouter from "./agent-spawn";
import agentRuntimeRouter from "./agent-runtime";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import agentDomainsRouter from "./domains";
import domainResolveRouter from "./domain-resolve";
import marketplaceRouter from "./marketplace";
import paymentsRouter from "./payments";
import jobsRouter from "./jobs";
import mailRouter from "./mail";
import resendWebhooksRouter from "./resend-webhooks";
import agentPaymentsRouter from "./agent-payments";
import resolveRouter, { handleReverse, handleAgentDiscovery } from "./resolve";
import integrationsRouter from "./integrations";
import organizationsRouter from "./organizations";
import humansRouter from "./humans";
import agentWebhooksRouter from "./agent-webhooks";
import agentAttestationsRouter from "./agent-attestations";
import { controlPlaneAgentRouter, controlPlaneVerifyRouter } from "./control-plane";
import governanceRouter from "./governance";
import agenticPayRouter from "./agentic-pay";
import metaRouter from "./meta";
import walletRouter from "./wallet";
import { ownerTokenRouter, agentLinkOwnerRouter } from "./owner-tokens";
import bootstrapRouter from "./bootstrap";
import { requireInboxAccess, requireAgentPlan, requirePlan, checkAgentLimit } from "../../middlewares/feature-gate";
import { tryAgentAuth } from "../../middlewares/agent-auth";
import agentAuthRouter from "./agent-auth";
import oauthClientsRouter from "./oauth-clients";
import agentOAuthTokensRouter from "./agent-oauth-tokens";
import adminRouter from "./admin";
import claimHistoryRouter from "./claim-history";
import orgPoliciesRouter from "./org-policies";
import mppRouter from "./mpp";
import waitlistRouter from "./waitlist";
import nftRouter from "./nft";
import agentCardRouter from "./agent-card";
import reputationFeedbackRouter from "./reputation-feedback";
import a2aRouter from "./a2a";

const router = Router();

router.use("/resolve", resolutionRateLimit, resolveRouter);
router.post("/reverse", resolutionRateLimit, handleReverse);
router.get("/agents", (req, res, next) => {
  const hasDiscoveryParams = req.query.q || req.query.capability || req.query.minTrust || req.query.protocol || req.query.verifiedOnly || req.query.sort || req.query.limit || req.query.offset;
  const hasAuthHeader = req.headers["authorization"] || req.headers["x-api-key"] || req.cookies?.sid;
  if (hasDiscoveryParams && !hasAuthHeader) {
    return handleAgentDiscovery(req, res, next);
  }
  return next();
});
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/users/me/api-keys", apiKeysRouter);
router.use("/users/me/identities", identitiesRouter);
router.post("/agents", (req, res, next) => {
  const handle: string = (req.body?.handle ?? "").toLowerCase();
  const handleLen = handle.replace(/[^a-z0-9]/g, "").length;
  if (handleLen >= 5) {
    return checkAgentLimit()(req, res, next);
  }
  return requirePlan("starter")(req, res, () => checkAgentLimit()(req, res, next));
});
router.use("/agents", agentsRouter);
router.use("/agents", agentVerificationRouter);
router.use("/agents", agentDomainsRouter);
router.use("/agents", agentSpawnRouter);
router.use("/agents", agentRuntimeRouter);
router.use("/agents", agentTransfersRouter);
router.use("/agents", agentRegistryRouter);
router.use("/agents", agentPaymentsRouter);
router.use("/handles", handlesRouter);
router.use("/fleet", requirePlan("pro"), fleetRouter);
router.use("/analytics", requirePlan("pro"), dashboardRouter);
router.use("/p", publicProfilesRouter);
router.use("/public/agents", agentIdentityRouter);
router.use("/programmatic", registrationRateLimit, programmaticRouter);
router.use("/tasks", tryAgentAuth, requireAgentPlan("starter"), tasksRouter);
router.use("/dashboard", requirePlan("pro"), dashboardRouter);
router.use("/billing", billingRouter);
router.use("/webhooks", webhooksRouter);
router.use("/domains", resolutionRateLimit, domainResolveRouter);
router.use("/marketplace", marketplaceRouter);
router.use("/payments", paymentsRouter);
router.use("/jobs", jobsRouter);
router.use("/mail", tryAgentAuth, requireInboxAccess(), mailRouter);
router.use("/webhooks", resendWebhooksRouter);
router.use("/integrations", integrationsRouter);
router.use("/orgs", requirePlan("pro"), organizationsRouter);
router.use("/org", requirePlan("pro"), organizationsRouter);
router.use("/pay", agenticPayRouter);
router.use("/humans", humansRouter);
router.use("/agents", agentWebhooksRouter);
router.use("/agents", agentAttestationsRouter);
router.use("/agents", walletRouter);
router.use("/agents", controlPlaneAgentRouter);
router.use("/", governanceRouter);
router.use("/agents", governanceRouter);
router.use("/", controlPlaneVerifyRouter);
router.use("/meta", metaRouter);
router.use("/owner-tokens", ownerTokenRouter);
router.use("/agents", agentLinkOwnerRouter);
router.use("/auth", agentAuthRouter);
router.use("/clients", oauthClientsRouter);
router.use("/agents", agentOAuthTokensRouter);
router.use("/admin", adminRouter);
router.use("/agents", claimHistoryRouter);
router.use("/orgs/:orgId/policies", orgPoliciesRouter);
router.use("/bootstrap", bootstrapRouter);
router.use("/mpp", mppRouter);
router.use("/waitlist", waitlistRouter);
router.use("/agent-card", agentCardRouter);
router.use("/agents", reputationFeedbackRouter);
router.use("/", nftRouter);
router.use("/a2a", a2aRouter);

export default router;
