import { Router } from "express";
import { resolutionRateLimit, registrationRateLimit } from "../../middlewares/rate-limit";
import authRouter from "./auth";
import usersRouter from "./users";
import apiKeysRouter from "./api-keys";
import identitiesRouter from "./identities";
import agentsRouter from "./agents";
import handlesRouter from "./handles";
import agentTransfersRouter from "./agent-transfers";
import fleetRouter from "./fleet";
import agentRegistryRouter from "./agent-registry";
import publicProfilesRouter from "./public-profiles";
import programmaticRouter from "./programmatic";
import agentVerificationRouter from "./agent-verification";
import agentIdentityRouter from "./agent-identity";
import agentSpawnRouter from "./agent-spawn";
import agentRuntimeRouter from "./agent-runtime";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import agentDomainsRouter from "./domains";
import domainResolveRouter from "./domain-resolve";
import marketplaceRouter from "./marketplace";
import paymentsRouter from "./payments";
import jobsRouter from "./jobs";
import mailRouter from "./mail";
import resendWebhooksRouter from "./resend-webhooks";
import agentPaymentsRouter from "./agent-payments";
import resolveRouter, { handleReverse, handleAgentDiscovery } from "./resolve";
import integrationsRouter from "./integrations";
import organizationsRouter from "./organizations";
import humansRouter from "./humans";
import agentWebhooksRouter from "./agent-webhooks";
import agentAttestationsRouter from "./agent-attestations";
import { controlPlaneAgentRouter, controlPlaneVerifyRouter } from "./control-plane";

const router = Router();

router.use("/resolve", resolutionRateLimit, resolveRouter);
router.post("/reverse", resolutionRateLimit, handleReverse);
router.get("/agents", (req, res, next) => {
  const hasDiscoveryParams = req.query.q || req.query.capability || req.query.minTrust || req.query.protocol || req.query.verifiedOnly || req.query.sort || req.query.limit || req.query.offset;
  const hasAuthHeader = req.headers["x-replit-user-id"] || req.headers["x-agentid-user-id"] || req.headers["authorization"];
  if (hasDiscoveryParams && !hasAuthHeader) {
    return handleAgentDiscovery(req, res, next);
  }
  return next();
});
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/users/me/api-keys", apiKeysRouter);
router.use("/users/me/identities", identitiesRouter);
router.use("/agents", agentsRouter);
router.use("/agents", agentVerificationRouter);
router.use("/agents", agentDomainsRouter);
router.use("/agents", agentSpawnRouter);
router.use("/agents", agentRuntimeRouter);
router.use("/agents", agentTransfersRouter);
router.use("/agents", agentRegistryRouter);
router.use("/agents", agentPaymentsRouter);
router.use("/handles", handlesRouter);
router.use("/fleet", fleetRouter);
router.use("/p", publicProfilesRouter);
router.use("/public/agents", agentIdentityRouter);
router.use("/programmatic", registrationRateLimit, programmaticRouter);
router.use("/tasks", tasksRouter);
router.use("/dashboard", dashboardRouter);
router.use("/billing", billingRouter);
router.use("/webhooks", webhooksRouter);
router.use("/domains", resolutionRateLimit, domainResolveRouter);
router.use("/marketplace", marketplaceRouter);
router.use("/payments", paymentsRouter);
router.use("/jobs", jobsRouter);
router.use("/mail", mailRouter);
router.use("/webhooks", resendWebhooksRouter);
router.use("/integrations", integrationsRouter);
router.use("/orgs", organizationsRouter);
router.use("/org", organizationsRouter);
router.use("/humans", humansRouter);
router.use("/agents", agentWebhooksRouter);
router.use("/agents", agentAttestationsRouter);
router.use("/agents", controlPlaneAgentRouter);
router.use("/", controlPlaneVerifyRouter);

export default router;
