import { Footer } from '@/components/Footer';

export function Security() {
  return (
    <div className="pt-16" style={{ background: 'var(--bg-base)' }}>
      <div className="max-w-[740px] mx-auto px-6 py-20">
        <h1
          className="text-3xl md:text-4xl font-bold mb-2"
          style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}
        >
          Responsible Disclosure Policy
        </h1>
        <p className="text-sm mb-12" style={{ color: 'var(--text-dim)' }}>
          Last updated: March 17, 2026
        </p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>
          <section>
            <h2
              className="text-lg font-semibold mb-3"
              style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-display)' }}
            >
              Our Commitment
            </h2>
            <p>
              Agent ID takes the security of our platform seriously. We appreciate the work of
              security researchers who help us protect our users and infrastructure. If you believe
              you have discovered a security vulnerability, we encourage you to report it to us
              responsibly.
            </p>
            <p className="mt-3">
              We commit to acknowledging reports within 3 business days, providing status updates
              throughout our investigation, and crediting researchers (with their permission) when
              we publish fixes.
            </p>
          </section>

          <section>
            <h2
              className="text-lg font-semibold mb-3"
              style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-display)' }}
            >
              Scope
            </h2>
            <p className="mb-3">The following properties are in scope:</p>
            <ul className="space-y-1 ml-4">
              {[
                'getagent.id (main application)',
                'api.getagent.id (REST API)',
                'mcp.getagent.id (MCP server)',
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span style={{ color: 'var(--accent)', flexShrink: 0 }}>–</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mt-4 mb-3">Out of scope:</p>
            <ul className="space-y-1 ml-4">
              {[
                'Social engineering attacks against Agent ID staff',
                'Denial-of-service or volumetric attacks',
                'Vulnerabilities in third-party services we depend on',
                'Issues requiring physical access to our infrastructure',
                'Reports generated by automated scanners without manual validation',
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span style={{ color: 'var(--text-dim)', flexShrink: 0 }}>–</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2
              className="text-lg font-semibold mb-3"
              style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-display)' }}
            >
              Disclosure Process
            </h2>
            <ol className="space-y-3 ml-4 list-decimal list-inside">
              <li>
                Email your report to{' '}
                <a
                  href="mailto:security@getagent.id"
                  style={{ color: 'var(--accent)' }}
                >
                  security@getagent.id
                </a>{' '}
                with a clear description of the vulnerability, reproduction steps, and potential
                impact.
              </li>
              <li>
                We will acknowledge receipt within 3 business days and assign a tracking
                reference.
              </li>
              <li>
                We will investigate and aim to provide a resolution timeline within 10 business
                days of validation.
              </li>
              <li>
                Please do not publicly disclose the vulnerability until we have released a fix or
                90 days have elapsed, whichever comes first.
              </li>
              <li>
                We will notify you when the fix is deployed and, with your permission, credit you
                in our release notes.
              </li>
            </ol>
          </section>

          <section>
            <h2
              className="text-lg font-semibold mb-3"
              style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-display)' }}
            >
              Safe Harbor
            </h2>
            <p>
              We will not pursue legal action against researchers who discover and report
              vulnerabilities in good faith under this policy, provided they do not: access or
              exfiltrate user data beyond what is required to demonstrate the issue, perform
              actions that degrade service availability, or engage in activities that violate
              applicable laws beyond what is strictly necessary to demonstrate the vulnerability.
            </p>
          </section>

          <section>
            <h2
              className="text-lg font-semibold mb-3"
              style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-display)' }}
            >
              Contact
            </h2>
            <p>
              Email:{' '}
              <a href="mailto:security@getagent.id" style={{ color: 'var(--accent)' }}>
                security@getagent.id
              </a>
            </p>
            <p className="mt-2">
              For encrypted communications, please contact us directly at the email above.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
}
