// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding/Step1_Welcome.tsx": () => import("../components/mockups/onboarding/Step1_Welcome.tsx"),
  "./components/mockups/onboarding/Step2_SignIn.tsx": () => import("../components/mockups/onboarding/Step2_SignIn.tsx"),
  "./components/mockups/onboarding/Step3_Identity.tsx": () => import("../components/mockups/onboarding/Step3_Identity.tsx"),
  "./components/mockups/onboarding/Step4_Verify.tsx": () => import("../components/mockups/onboarding/Step4_Verify.tsx"),
  "./components/mockups/onboarding/Step5_Capabilities.tsx": () => import("../components/mockups/onboarding/Step5_Capabilities.tsx"),
  "./components/mockups/onboarding/Step6_Complete.tsx": () => import("../components/mockups/onboarding/Step6_Complete.tsx"),
  "./components/mockups/pricing/PricingAtlas.tsx": () => import("../components/mockups/pricing/PricingAtlas.tsx"),
  "./components/mockups/pricing/PricingGravity.tsx": () => import("../components/mockups/pricing/PricingGravity.tsx"),
  "./components/mockups/signin/Redesign.tsx": () => import("../components/mockups/signin/Redesign.tsx"),
  "./components/mockups/get-started/CenteredHero.tsx": () => import("../components/mockups/get-started/CenteredHero.tsx"),
  "./components/mockups/get-started/SplitScreen.tsx": () => import("../components/mockups/get-started/SplitScreen.tsx"),
  "./components/mockups/agent-id/AgentID.tsx": () => import("../components/mockups/agent-id/AgentID.tsx"),
  "./components/mockups/agent-id/CardBare.tsx": () => import("../components/mockups/agent-id/CardBare.tsx"),
  "./components/mockups/agent-id/CardLinked.tsx": () => import("../components/mockups/agent-id/CardLinked.tsx"),
  "./components/mockups/agent-id/CardShowcaseV2.tsx": () => import("../components/mockups/agent-id/CardShowcaseV2.tsx"),
  "./components/mockups/agent-id/ConceptDark.tsx": () => import("../components/mockups/agent-id/ConceptDark.tsx"),
  "./components/mockups/agent-id/ConceptLight.tsx": () => import("../components/mockups/agent-id/ConceptLight.tsx"),
  "./components/mockups/agent-id/HandleNFT.tsx": () => import("../components/mockups/agent-id/HandleNFT.tsx"),
  "./components/mockups/agent-id/HeroA.tsx": () => import("../components/mockups/agent-id/HeroA.tsx"),
  "./components/mockups/agent-id/HeroB.tsx": () => import("../components/mockups/agent-id/HeroB.tsx"),
  "./components/mockups/agent-id/HomeGrid.tsx": () => import("../components/mockups/agent-id/HomeGrid.tsx"),
  "./components/mockups/agent-id/HomeOrb.tsx": () => import("../components/mockups/agent-id/HomeOrb.tsx"),
  "./components/mockups/agent-id/HomeSignal.tsx": () => import("../components/mockups/agent-id/HomeSignal.tsx"),
  "./components/mockups/agent-id/IssuanceFilm.tsx": () => import("../components/mockups/agent-id/IssuanceFilm.tsx")
};
