// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agent-id/AgentID.tsx": () => import("../components/mockups/agent-id/AgentID.tsx"),
  "./components/mockups/agent-id/ConceptDark.tsx": () => import("../components/mockups/agent-id/ConceptDark.tsx"),
  "./components/mockups/agent-id/ConceptLight.tsx": () => import("../components/mockups/agent-id/ConceptLight.tsx"),
  "./components/mockups/agent-id/HeroA.tsx": () => import("../components/mockups/agent-id/HeroA.tsx"),
  "./components/mockups/agent-id/HeroB.tsx": () => import("../components/mockups/agent-id/HeroB.tsx"),
  "./components/mockups/agent-id/HomeGrid.tsx": () => import("../components/mockups/agent-id/HomeGrid.tsx"),
  "./components/mockups/agent-id/HomeOrb.tsx": () => import("../components/mockups/agent-id/HomeOrb.tsx"),
  "./components/mockups/agent-id/HomeSignal.tsx": () => import("../components/mockups/agent-id/HomeSignal.tsx"),
  "./components/mockups/agent-id/IssuanceFilm.tsx": () => import("../components/mockups/agent-id/IssuanceFilm.tsx")
};
